from datetime import UTC, date, datetime

from fastapi import HTTPException, status
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from app.models.charge import Charge, ChargeStatus, ChargeType
from app.models.daily_operation import (
    DailyOperationRun,
    DailyOperationStatus,
)
from app.models.extension import Extension, ExtensionStatus
from app.models.service import Service
from app.schemas.daily_operation import DailyOperationRead
from app.services.audit import record_audit_event
from app.services.billing import apply_credit_to_charge
from app.services.pricing import agreed_price_for_period


def month_start(value: date) -> date:
    return value.replace(day=1)


def next_month(value: date) -> date:
    if value.month == 12:
        return date(value.year + 1, 1, 1)
    return date(value.year, value.month + 1, 1)


def responsible_customer_id(service: Service, due_date: date):
    holder = next(
        (
            item
            for item in service.holders
            if item.start_date <= due_date
            and (item.end_date is None or item.end_date > due_date)
        ),
        None,
    )
    if holder is None:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=(
                f"Service {service.id} has no holder for "
                f"{due_date.isoformat()}"
            ),
        )
    return holder.customer_id


def charge_candidates(run_date: date, db: Session) -> list[Service]:
    period = month_start(run_date)
    services = db.scalars(
        select(Service).where(Service.activation_date.is_not(None))
    ).all()
    existing = set(
        db.scalars(
            select(Charge.service_id).where(
                Charge.charge_type == ChargeType.monthly,
                Charge.billing_period == period,
            )
        )
    )
    candidates: list[Service] = []
    for service in services:
        first_period = next_month(month_start(service.activation_date))
        due_date = period.replace(day=service.payment_day)
        if (
            period >= first_period
            and due_date <= run_date
            and service.id not in existing
            and (
                service.cancellation_date is None
                or due_date <= service.cancellation_date
            )
        ):
            candidates.append(service)
    return candidates


def expired_extensions(run_date: date, db: Session) -> list[Extension]:
    return list(
        db.scalars(
            select(Extension).where(
                Extension.status == ExtensionStatus.active,
                Extension.promised_date < run_date,
            )
        )
    )


def execute_daily_operations(
    run_date: date,
    dry_run: bool,
    executed_by: str,
    db: Session,
) -> DailyOperationRead:
    if run_date > date.today():
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Daily operations cannot run for a future date",
        )
    existing_run = db.scalar(
        select(DailyOperationRun).where(
            DailyOperationRun.run_date == run_date
        )
    )
    if existing_run is not None:
        return DailyOperationRead.model_validate(existing_run).model_copy(
            update={"dry_run": False}
        )

    services = charge_candidates(run_date, db)
    extensions = expired_extensions(run_date, db)
    if dry_run:
        return DailyOperationRead(
            run_date=run_date,
            dry_run=True,
            monthly_charges_created=len(services),
            extensions_expired=len(extensions),
            executed_by=executed_by,
        )

    period = month_start(run_date)
    for service in services:
        due_date = period.replace(day=service.payment_day)
        agreed_price = agreed_price_for_period(
            service.id,
            period,
            service.monthly_price,
            db,
        )
        charge = Charge(
            customer_id=responsible_customer_id(service, due_date),
            service_id=service.id,
            charge_type=ChargeType.monthly,
            description=f"Monthly service {period:%Y-%m}",
            amount=agreed_price,
            outstanding_balance=agreed_price,
            due_date=due_date,
            billing_period=period,
            status=ChargeStatus.pending,
            generated_by=executed_by,
            notes="Generated by daily operations",
        )
        db.add(charge)
        db.flush()
        apply_credit_to_charge(charge, executed_by, db)

    for extension in extensions:
        previous_status = extension.status
        extension.status = ExtensionStatus.expired
        extension.resolved_at = datetime.now(UTC)
        extension.resolution_reason = "Promised payment date elapsed"
        record_audit_event(
            db,
            actor=executed_by,
            action="extension.expired",
            entity_type="Extension",
            entity_id=extension.id,
            reason=extension.resolution_reason,
            before_data={"status": previous_status},
            after_data={"status": extension.status},
        )

    run = DailyOperationRun(
        run_date=run_date,
        status=DailyOperationStatus.completed,
        monthly_charges_created=len(services),
        extensions_expired=len(extensions),
        executed_by=executed_by,
    )
    db.add(run)
    try:
        db.flush()
        record_audit_event(
            db,
            actor=executed_by,
            action="operations.daily_completed",
            entity_type="DailyOperationRun",
            entity_id=run.id,
            reason=f"Daily operations for {run_date.isoformat()}",
            after_data={
                "monthly_charges_created": len(services),
                "extensions_expired": len(extensions),
            },
        )
        db.commit()
    except IntegrityError as exc:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Daily operations collided with another execution",
        ) from exc
    db.refresh(run)
    return DailyOperationRead.model_validate(run).model_copy(
        update={"dry_run": False}
    )
